routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('sitemap.xml', function (){
   return view('sitemap');
})->name('page.sitemap');
Route::get('/', 'PageController@index')->name('page.home');
Route::get('package/{package}', 'PageController@showPackage')->name('page.single');
Route::get('all/package', 'PageController@showAllPackage')->name('page.all');
Route::get('category/{category}/packges', 'PageController@showAllPackage')->name('page.category');
Route::post('packages/search', 'PageController@showAllPackage')->name('packages.search');
Route::get('about', 'PageController@about')->name('page.about');
Route::get('categories', 'PageController@categories')->name('page.categories');
Route::get('contact', 'PageController@contact')->name('page.contact');
Route::get('blog', 'PageController@blog')->name('page.blog');


Route::post('booking/request', 'PageController@bookTourRequest')->name('booking.request');
Route::post('contact/request', 'PageController@contactUsRequest')->name('contact.request');

Route::get('admin', 'DashboardController@admin')->name('dashboard.admin');
//Route::get('debug', 'DashboardController@debug')->name('dashboard.debug');
//
//Route::resource('category', 'CategoryController');
//Route::resource('packages', 'PackageController');
////
//Route::resource('category', 'CategoryController');
//Route::resource('packages', 'PackageController');
//Route::resource('package-timelines', 'PackageTimelineController');
//
//Route::get('package/{package}/timeline', 'PackageController@singlepackage')->name('timeline.single');
//Route::get('package/{package}/timeline/form', 'PackageController@packageTimeLineAddForm')->name('timeline.form');
////
//Route::get('package/{package}/images', 'PackageController@images')->name('package.images');
//Route::get('package/{package}/images-form', 'PackageController@imageForm')->name('package.imagesform');
//Route::post('package/{package}/images-form', 'PackageController@saveImage')->name('package.imagesform');
//
Route::resource('comments', 'CommentController');

Auth::routes();

Route::prefix('admin')->middleware(['auth'])->group(function () {
    Route::get('/comments/all', 'DashboardController@comments')->name('all.comments');
    Route::get('/comment/{comment}/show', 'DashboardController@showComment')->name('show.comment');
    Route::get('/comment/{comment}/approve', 'DashboardController@approveComment')->name('approve.comment');
    Route::get('/comment/{comment}/disapprove', 'DashboardController@disapproveComment')->name('disapprove.comment');
    Route::get('/comment/{comment}/reply', 'DashboardController@reply')->name('reply.comment');
    Route::post('/comment/{comment}/reply-save', 'DashboardController@saveReply')->name('reply.save');
});
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');

resources/views/about.blade.php
@extends('layouts.default')

@section('content')
    <section class="breadcrumb-outer text-center">
        <div class="container">
            <div class="breadcrumb-content">
                <h2>About Us</h2>
            </div>
        </div>
        <div class="section-overlay"></div>
    </section>

    <!-- About Us -->
    <section class="aboutus">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <div class="section-title text-center">
                        <h2>Why Choose Us?</h2>
                        <div class="section-icon section-icon-white">
                            <i class="flaticon-diamond"></i>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4 col-sm-6 col-xs-12">
                    <div class="about-item">
                        <div class="about-icon">
                            <i class="fa fa-superpowers" aria-hidden="true"></i>
                        </div>
                        <div class="about-content">
                            <h3>Perfect Planning</h3>
                            <p>Plan your perfect vacation with our travel agency. Choose among hundreds of all-inclusive offers!</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 col-sm-6 col-xs-12">
                    <div class="about-item">
                        <div class="about-icon">
                            <i class="fa fa-paw" aria-hidden="true"></i>
                        </div>
                        <div class="about-content">
                            <h3>Secure Venues</h3>
                            <p>We work hard to secure the best hotel rates in the most popular destinations. Search and book adventure tours now!</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 col-sm-6 col-xs-12">
                    <div class="about-item">
                        <div class="about-icon">
                            <i class="fa fa-fire" aria-hidden="true"></i>
                        </div>
                        <div class="about-content">
                            <h3>Beautiful Memories</h3>
                            <p>Book international vacation packages with us and create memories that will last a lifetime! Create History !</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- About Us Ends -->

    @include('pages.home.testimonials')

    <section class="contact">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <div id="contact-form" class="contact-form">

                        <div id="contactform-error-msg"></div>

                        <form method="post" action="{{route('contact.request')}}">
                            @csrf
                            <div class="row">
                                <div class="form-group col-xs-12">
                                    <label>Name:</label>
                                    <input type="text" name="name" class="form-control" id="name" placeholder="Enter full name" required>
                                </div>
                                <div class="form-group col-xs-6">
                                    <label>Email:</label>
                                    <input type="email" name="email" class="form-control" id="email" placeholder="abc@xyz.com" required>
                                </div>
                                <div class="form-group col-xs-6 col-left-padding">
                                    <label>Phone Number:</label>
                                    <input type="text" name="telephone" class="form-control" id="telephone" placeholder="XXXX-XXXXXX" required>
                                </div>
                                <div class="textarea col-xs-12">
                                    <label>Message:</label>
                                    <textarea name="message" placeholder="Enter a message" required></textarea>
                                </div>
                                <div class="col-xs-12">
                                    <div class="comment-btn">
                                        <input type="submit" class="btn-blue btn-red"  value="Send Message">
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="contact-about footer-margin">
                        <div class="about-logo">
                           <h3> Sri Lanka Tour Go</h3>
{{--                            <img src="images/Yatra-01.png" alt="Image">--}}
                        </div>
                        <h4>Travel With Us</h4>
                        <p>The Best Travel Agent in Sri lanka to give most worth to your holiday in Sri Lanka</p>
                        <div class="contact-location">
                            <ul>
                                <li><i class="flaticon-maps-and-flags" aria-hidden="true"></i> {{$agent->address}}</li>
                                <li><i class="flaticon-phone-call"></i> <a
                                        href="tel:{{$agent->telephone}}">{{$agent->telephone}}</a></li>
                                <li><i class="flaticon-mail"></i>  <a href="mailto:{{$agent->email}}">{{$agent->email}}</a></li>
                            </ul>
                        </div>
                        <div class="footer-social-links">
                            <ul>
                                @if($agent->facebook)
                                    <li class="social-icon"><a target="_blank" href="{{$agent->facebook}}"><i class="fa fa-facebook"
                                                                                              aria-hidden="true"></i></a>
                                    </li>
                                @endif
                                @if($agent->insta)
                                    <li class="social-icon"><a target="_blank" href="{{$agent->insta}}"><i class="fa fa-instagram"
                                                                                           aria-hidden="true"></i></a>
                                    </li>
                                @endif
                                @if($agent->twitter)
                                    <li class="social-icon"><a target="_blank" href="{{$agent->twitter}}"><i class="fa fa-twitter"
                                                                                             aria-hidden="true"></i></a>
                                    </li>
                                @endif
                                @if($agent->youtube)
                                    <li class="social-icon"><a target="_blank" target="_blank" href="{{$agent->youtube}}">
                                            <i class="fa fa-youtube" aria-hidden="true"></i></a>
                                    </li>
                                @endif
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@stop

resources/views/all-packages.blade.php
@extends('layouts.default')

@section('content')
    <section class="breadcrumb-outer text-center">
        <div class="container">
            <div class="breadcrumb-content">
                <h2>All Packages</h2>
            </div>
        </div>
        <div class="section-overlay"></div>
    </section>
    <!-- BreadCrumb Ends -->

    <!-- Listing -->
    <section class="blog-list grid-list">
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-sm-12">
                    <div class="blog-wrapper">
                        <div class="row">
                            @foreach($packages as $package)
                                <div class="col-sm-6 col-xs-12">
                                    <div class="blog-item">
                                        <div class="blog-image">
                                            <img class="img-pck" src="{{asset('images/packages/'.$package->image)}}" alt="Image">
                                        </div>
                                        <div class="blog-content">
                                            <h3>
                                                <a href="{{route('page.single',['package'=>$package->id])}}">{{$package->name}}</a>
                                            </h3>
                                            <p> {{$package->packageDescription->other}} </p>

                                            <div class="blog-author">
                                                <div class="pull-left">
                                                    <p><i class="flaticon-time"></i> {{$package->packageDescription->duration}}</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            @endforeach
                        </div>
                    </div>

                    @if($packages instanceof \Illuminate\Pagination\LengthAwarePaginator )
                        <div class="col-sm-12">
                            <div class="pagination-content">
                                {{ $packages->links() }}
                            </div>
                        </div>
                    @endif

                </div>


                <div id="sidebar-sticky" class="col-md-4 col-sm-12">
                    <aside class="detail-sidebar sidebar-wrapper">
                        <div class="item-sidebar">
                            <div class="sidebar-item sidebar-item-dark">
                                <div class="detail-title">
                                    <h3>Search</h3>
                                </div>
                                <form action="{{route('packages.search')}}" method="post">
                                    @csrf
                                    <div class="row">
                                        <div class="form-group col-xs-12">
                                            <input type="text" class="form-control" name="search"
                                                   placeholder="Enter the place you want to search">
                                        </div>
                                        <div class="col-xs-12">
                                            <div class="comment-btn">
                                                <button type="submit" class="btn-blue btn-red">Search Now</button>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                            <div class="post-categories sidebar-item">
                                <div class="detail-title">
                                    <h3>Categories</h3>
                                </div>
                                <ul>
                                    @foreach($categories as $category)
                                        <li>
                                            <a href="{{route('page.category',['category'=>$category->id])}}">{{$category->name}}</a>
                                        </li>
                                    @endforeach
                                </ul>
                            </div>
                            <div class="popular-post sidebar-item">
                                <div class="detail-title">
                                    <h3>Popular Trips</h3>
                                </div>
                                @foreach($popularPackages as $key => $popularPackage)
                                    <div class="popular-item">
                                        <div class="popular-content">
                                            <span class="item-no">{{++$key}}</span>
                                            <h4>
                                                <a href="{{route('page.single',['package'=>$popularPackage->package_id])}}">{{$popularPackage->package->name}}</a>
                                            </h4>
                                        </div>
                                    </div>
                                @endforeach
                            </div>
                        </div>
                    </aside>
                </div>
            </div>
        </div>
    </section>
    <style>
        .img-pck{
            height: 240px !important;
        }
    </style>
@stop

resources/views/categories.blade.php
@extends('layouts.default')

@section('content')

@stop

resources/views/comment-form.blade.php
<div class="comment-form">
    <form role="form" action="{{route('comments.store')}}" method="post" enctype="multipart/form-data">
        <input type="hidden" name="package_id" value="{{$package->id}}">
        @csrf
        <h3>Add a comment</h3>
        <div class="row">
            <div class="form-group col-sm-12">
                <label for="Name">Your Comment:</label>
                <textarea type="text" name="comment" required></textarea>
            </div>
            <div class="form-group col-sm-6">
                <label for="Name">Name:</label>
                <input type="text" name="name" class="form-control" required id="Name">
            </div>
            <div class="form-group col-sm-6">
                <label for="email">Email address:</label>
                <input type="email" name="email" class="form-control" required id="email">
            </div>
            <div class="col-sm-12">
                <div class="comment-btn">
                    <button class="btn-blue btn-red">Submit Comment</button>
                </div>
            </div>
        </div>
    </form>
</div>

resources/views/contact.blade.php
@extends('layouts.default')

@section('content')
    <section class="breadcrumb-outer text-center">
        <div class="container">
            <div class="breadcrumb-content">
                <h2>Contact Us</h2>
            </div>
        </div>
        <div class="section-overlay"></div>
    </section>
    <!-- BreadCrumb Ends -->

    <section class="contact">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <div id="contact-form" class="contact-form">

                        <div id="contactform-error-msg"></div>

                        <form method="post" action="#" name="contactform" id="contactform">
                            <div class="row">
                                <div class="form-group col-xs-12">
                                    <label>Name:</label>
                                    <input type="text" name="full_name" class="form-control" id="Name" placeholder="Enter full name" required>
                                </div>
                                <div class="form-group col-xs-6">
                                    <label>Email:</label>
                                    <input type="email" name="email" class="form-control" id="email" placeholder="abc@xyz.com" required>
                                </div>
                                <div class="form-group col-xs-6 col-left-padding">
                                    <label>Phone Number:</label>
                                    <input type="text" name="phone" class="form-control" id="phnumber" placeholder="XXXX-XXXXXX" required>
                                </div>
                                <div class="textarea col-xs-12">
                                    <label>Message:</label>
                                    <textarea name="comments" placeholder="Enter a message" required></textarea>
                                </div>
                                <div class="col-xs-12">
                                    <div class="comment-btn">
                                        <input type="submit" class="btn-blue btn-red" id="submit" value="Send Message">
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="contact-about footer-margin">
                        <div class="about-logo">
                            <img src="images/Yatra-01.png" alt="Image">
                        </div>
                        <h4>Travel With Us</h4>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.</p>
                        <div class="contact-location">
                            <ul>
                                <li><i class="flaticon-maps-and-flags" aria-hidden="true"></i> Location</li>
                                <li><i class="flaticon-phone-call"></i> (012)-345-6789</li>
                                <li><i class="flaticon-mail"></i> tourntravel@testmail.com</li>
                            </ul>
                        </div>
                        <div class="footer-social-links">
                            <ul>
                                <li class="social-icon"><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                                <li class="social-icon"><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                                <li class="social-icon"><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                                <li class="social-icon"><a href="#"><i class="fa fa-youtube" aria-hidden="true"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

@stop

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/sitemap.blade.php
<?xml version="1.0" encoding="UTF-8"?>
<urlset
    xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9
            http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">
    <!-- created with Free Online Sitemap Generator www.xml-sitemaps.com -->


    <url>
        <loc>http://srilankatourgo.com/</loc>
        <lastmod>2019-10-13T16:59:39+00:00</lastmod>
        <priority>1.00</priority>
    </url>
    <url>
        <loc>http://srilankatourgo.com/all/package</loc>
        <lastmod>2019-10-13T16:59:39+00:00</lastmod>
        <priority>0.80</priority>
    </url>
    <url>
        <loc>http://srilankatourgo.com/about</loc>
        <lastmod>2019-10-13T16:59:39+00:00</lastmod>
        <priority>0.80</priority>
    </url>
    <url>
        <loc>http://srilankatourgo.com/package/3</loc>
        <lastmod>2019-10-13T16:59:39+00:00</lastmod>
        <priority>0.80</priority>
    </url>
    <url>
        <loc>http://srilankatourgo.com/package/4</loc>
        <lastmod>2019-10-13T16:59:39+00:00</lastmod>
        <priority>0.80</priority>
    </url>
    <url>
        <loc>http://srilankatourgo.com/package/5</loc>
        <lastmod>2019-10-13T16:59:39+00:00</lastmod>
        <priority>0.80</priority>
    </url>
    <url>
        <loc>http://srilankatourgo.com/package/1</loc>
        <lastmod>2019-10-13T16:59:39+00:00</lastmod>
        <priority>0.80</priority>
    </url>
    <url>
        <loc>http://srilankatourgo.com/package/2</loc>
        <lastmod>2019-10-13T16:59:39+00:00</lastmod>
        <priority>0.80</priority>
    </url>
    <url>
        <loc>http://srilankatourgo.com/package/6</loc>
        <lastmod>2019-10-13T16:59:39+00:00</lastmod>
        <priority>0.64</priority>
    </url>
    <url>
        <loc>http://srilankatourgo.com/package/7</loc>
        <lastmod>2019-10-13T16:59:39+00:00</lastmod>
        <priority>0.64</priority>
    </url>
    <url>
        <loc>http://srilankatourgo.com/package/8</loc>
        <lastmod>2019-10-13T16:59:39+00:00</lastmod>
        <priority>0.64</priority>
    </url>
    <url>
        <loc>http://srilankatourgo.com/all/package?page=2</loc>
        <lastmod>2019-10-13T16:59:39+00:00</lastmod>
        <priority>0.64</priority>
    </url>
    <url>
        <loc>http://srilankatourgo.com/category/4/packges</loc>
        <lastmod>2019-10-13T16:59:39+00:00</lastmod>
        <priority>0.64</priority>
    </url>
    <url>
        <loc>http://srilankatourgo.com/category/10/packges</loc>
        <lastmod>2019-10-13T16:59:39+00:00</lastmod>
        <priority>0.64</priority>
    </url>
    <url>
        <loc>http://srilankatourgo.com/category/11/packges</loc>
        <lastmod>2019-10-13T16:59:39+00:00</lastmod>
        <priority>0.64</priority>
    </url>
    <url>
        <loc>http://srilankatourgo.com/category/13/packges</loc>
        <lastmod>2019-10-13T16:59:39+00:00</lastmod>
        <priority>0.64</priority>
    </url>
    <url>
        <loc>http://srilankatourgo.com/package/9</loc>
        <lastmod>2019-10-13T16:59:39+00:00</lastmod>
        <priority>0.51</priority>
    </url>
    <url>
        <loc>http://srilankatourgo.com/package/10</loc>
        <lastmod>2019-10-13T16:59:39+00:00</lastmod>
        <priority>0.51</priority>
    </url>
    <url>
        <loc>http://srilankatourgo.com/package/11</loc>
        <lastmod>2019-10-13T16:59:39+00:00</lastmod>
        <priority>0.51</priority>
    </url>
    <url>
        <loc>http://srilankatourgo.com/all/package?page=1</loc>
        <lastmod>2019-10-13T16:59:39+00:00</lastmod>
        <priority>0.51</priority>
    </url>


</urlset>